# -*- coding: utf-8 -*-
"""100 days of python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hRVWHnDNrnujD2Eb1nhlaHEcUBlQ9mb3

***Question 1. Printing***
"""

print("Day 1 - Python Print Function")
print("The function is declared like this:")
print("print('what to print')")

"""***Question 2. Debugging code***"""

print("Day 1 - String Manipulation")
print('String Concatenation is done with the "+" sign.')
print('e.g. print("Hello " + "world")')
print("New lines can be created with a backslash and n.")

"""***Question 3. Input Function***"""

print(len(input("What is your name? ")))

"""***Question 4. Variables***"""

# 🚨 Don't change the code below 👇
a = input("a: ")
b = input("b: ")
# 🚨 Don't change the code above 👆

####################################
#Write your code below this line 👇

c = a
a = b
b = c


#Write your code above this line 👆
####################################

# 🚨 Don't change the code below 👇
print("a: " + a)
print("b: " + b)

"""***Question 5. Band Name Generator***"""

print("Welcome to the Band Name Generator.")
street = input("What's the name of the city you grew up in?\n")
pet = input("What's your pet's name?\n")
print("Your band name could be " + street + " " + pet)

"""***Question 6. Data Types Conversion and addition***"""

# 🚨 Don't change the code below 👇
two_digit_number = input("Type a two digit number: ")
# 🚨 Don't change the code above 👆

####################################
#Write your code below this line 👇
first_number = two_digit_number[0]
second_number = two_digit_number[1]

print(int(first_number)+int(second_number))

"""***Question 7. BMI Calculator***"""

# 🚨 Don't change the code below 👇
height = input("enter your height in m: ")
weight = input("enter your weight in kg: ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
print(int(float(weight)/(float(height) ** 2)))

"""***Question 8. Life In Weeks***"""

# 🚨 Don't change the code below 👇
age = input("What is your current age? ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
years_left = 90 - int(age)
number_of_days = years_left * 365
number_of_weeks = years_left * 52
number_of_months = years_left * 12

print(f"You have {number_of_days} days, {number_of_weeks} weeks, and {number_of_months} months left")

"""***Question 9. Tip Calculator End***"""

#If the bill was $150.00, split between 5 people, with 12% tip. 
#Each person should pay (150.00 / 5) * 1.12 = 33.6
#Round the result to 2 decimal places.
print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill?"))

tip_as_percent = tip / 100
total_tip_amount = bill * tip_as_percent
total_bill = bill + total_tip_amount
bill_per_person = total_bill / people
final_amount = round(bill_per_person, 2)


# FAQ: How to round to 2 decimal places?

# Find the answer in the Q&A here: https://www.udemy.com/course/100-days-of-code/learn/lecture/17965132#questions/13315048


print(f"Each person should pay: ${final_amount}")

"""***Question 10. Odd or Even***

"""

# 🚨 Don't change the code below 👇
number = int(input("Which number do you want to check? "))
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
if number % 2 == 0:
    print("This is an even number.")
else:
    print("This is an odd number.")

"""***Question 11. BMI Calculator***"""

# 🚨 Don't change the code below 👇
height = float(input("enter your height in m: "))
weight = float(input("enter your weight in kg: "))
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
bmi_value = weight/height**2
bmi_value = round(bmi_value)

if bmi_value <= 18.5:
    print(f"Your BMI is {bmi_value}, you are underweight.")
elif bmi_value > 18.5 and bmi_value <=25:
    print(f"Your BMI is {bmi_value}, you have a normal weight.")
elif bmi_value > 25 and bmi_value <=30:
    print(f"Your BMI is {bmi_value}, you are slightly overweight.")
elif bmi_value > 30 and bmi_value <=35:
    print(f"Your BMI is {bmi_value}, you are obese.")
elif bmi_value > 35:
    print(f"Your BMI is {bmi_value}, you are clinically obese.")
else:
    print(f"Your BMI is {bmi_value}, you are nothing.")

"""***Question 12. Leap Year***"""

# 🚨 Don't change the code below 👇
year = int(input("Which year do you want to check? "))
# 🚨 Don't change the code above 👆

#Write your code below this line 👇

leap_count =0
non_leap_count =0

if year % 4 == 0:
    leap_count = leap_count +1
else:
    non_leap_count = non_leap_count+1

if year % 100 != 0:
    leap_count = leap_count +1
else:
    non_leap_count = non_leap_count+1

if year % 400 == 0:
    leap_count = leap_count +1
else:
    non_leap_count = non_leap_count+1

if leap_count > non_leap_count:
    print("Leap year.")
else:
    print("Not leap year.")

"""***Question 13. Pizza order practice***"""

# 🚨 Don't change the code below 👇
print("Welcome to Python Pizza Deliveries!")
size = input("What size pizza do you want? S, M, or L ")
add_pepperoni = input("Do you want pepperoni? Y or N ")
extra_cheese = input("Do you want extra cheese? Y or N ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
total_bill = 0
if size == "S":
    total_bill = total_bill + 15
elif size == "M":
    total_bill = total_bill + 20
else:
    total_bill = total_bill + 25

if add_pepperoni == "Y" and  size == "S":
    total_bill = total_bill + 2
elif add_pepperoni == "Y" and  (size == "M" or  size == "L"):
    total_bill = total_bill + 3
else:
    total_bill = total_bill + 0

if extra_cheese == "Y":
    total_bill = total_bill + 1
else:
    total_bill = total_bill + 0

print(f"Your final bill is: ${total_bill}.")

"""***Question 14. Ending code***"""

print("Welcome to the rollercoaster!")
height = int(input("What is your height in cm? "))
bill = 0

if height >= 120:
  print("You can ride the rollercoaster!")
  age = int(input("What is your age? "))
  if age < 12:
    bill = 5
    print("Child tickets are $5.")
  elif age <= 18:
    bill = 7
    print("Youth tickets are $7.")
  elif age >= 45 and age <= 55:
    print("Everything is going to be ok. Have a free ride on us!")
  else:
    bill = 12
    print("Adult tickets are $12.")
  
  wants_photo = input("Do you want a photo taken? Y or N. ")
  if wants_photo == "Y":
    bill += 3
  
  print(f"Your final bill is ${bill}")

else:
  print("Sorry, you have to grow taller before you can ride.")

"""***Question 15. Love Calculator***"""

# 🚨 Don't change the code below 👇
print("Welcome to the Love Calculator!")
name1 = input("What is your name? \n")
name2 = input("What is their name? \n")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
name1_upper = name1.upper()
name2_upper = name2.upper()

total_true_count = name1_upper.count('T') + name2_upper.count('T') + name1_upper.count('R') + name2_upper.count('R') + name1_upper.count('U') + name2_upper.count('U') + name1_upper.count('E') + name2_upper.count('E')

total_love_count = name1_upper.count('L') + name2_upper.count('L') + name1_upper.count('O') + name2_upper.count('O') + name1_upper.count('V') + name2_upper.count('V') + name1_upper.count('E') + name2_upper.count('E')

total = str(total_true_count) + str(total_love_count)

if int(total) < 10 | int(total) > 90:
    print(f"Your score is {total}, you go together like coke and mentos.")
elif 40 < int(total) < 50:
    print(f"Your score is {total}, you are alright together.")
else:
    print(f"Your score is {total}.")

"""***Question 16. Treasure Island***"""

print('''
*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/_____ /
*******************************************************************************
''')
print("Welcome to Treasure Island.")
print("Your mission is to find the treasure.")

#Write your code below this line 👇

choice1 = input('You\'re at a cross road. Where do you want to go? Type "left" or "right" \n').lower()
if choice1 == "left":
  choice2 = input('You\'ve come to a lake. There is an island in the middle of the lake. Type "wait" to wait for a boat. Type "swim" to swim across. \n').lower()
  if choice2 == "wait":
    choice3 = input("You arrive at the island unharmed. There is a house with 3 doors. One red, one yellow and one blue. Which colour do you choose? \n").lower()
    if choice3 == "red":
      print("It's a room full of fire. Game Over.")
    elif choice3 == "yellow":
      print("You found the treasure! You Win!")
    elif choice3 == "blue":
      print("You enter a room of beasts. Game Over.")
    else:
      print("You chose a door that doesn't exist. Game Over.")
  else:
    print("You get attacked by an angry trout. Game Over.")
else:
  print("You fell into a hole. Game Over.")

"""***Question 17. Heads or Tails using Random Module***"""

#Remember to use the random module
#Hint: Remember to import the random module here at the top of the file. 🎲
	 
#Write the rest of your code below this line 👇
import random

coin_outcome = random.randint(0,1)

if coin_outcome == 0:
    print("Tails")
else:
    print("Heads")

"""***Question 18. Guess who is paying the bill today***"""

# Import the random module here

# Split string method
names_string = input("Give me everybody's names, separated by a comma. ")
names = names_string.split(", ")
# 🚨 Don't change the code above 👆

#Write your code below this line 👇
import random
choice = random.randint(0,len(names)-1)

print(f"{names[choice]} is going to buy the meal today!")

"""***Question 19. Treasure Map***"""

# 🚨 Don't change the code below 👇
row1 = ["⬜️","️⬜️","️⬜️"]
row2 = ["⬜️","⬜️","️⬜️"]
row3 = ["⬜️️","⬜️️","⬜️️"]
map = [row1, row2, row3]
print(f"{row1}\n{row2}\n{row3}")
position = input("Where do you want to put the treasure? ")
# 🚨 Don't change the code above 👆

#Write your code below this row 👇
horizontal = int(position[0])
vertical = int(position[1])

map[vertical-1][horizontal-1] = "X"

#Write your code above this row 👆

# 🚨 Don't change the code below 👇
print(f"{row1}\n{row2}\n{row3}")

"""***Question 20. Average Height***"""

# 🚨 Don't change the code below 👇
student_heights = input("Input a list of student heights ").split()
for n in range(0, len(student_heights)):
  student_heights[n] = int(student_heights[n])
# 🚨 Don't change the code above 👆


#Write your code below this row 👇
total = 0
for ith in student_heights:
    total = total + ith

print(round(total/len(student_heights)))

"""***Question 21. High Score***"""

# 🚨 Don't change the code below 👇
student_scores = input("Input a list of student scores ").split()
for n in range(0, len(student_scores)):
  student_scores[n] = int(student_scores[n])
print(student_scores)
# 🚨 Don't change the code above 👆

#Write your code below this row 👇
highest = 0
for ith in range(0,len(student_scores)):
    if student_scores[ith] > highest:
        highest = student_scores[ith]

print("The highest score in the class is:",highest)

"""***Question 22. Adding Even Numbers***"""

#Write your code below this row 👇
total = 0
sum_even_number = range(101)

for i in sum_even_number:
    if i % 2  == 0:
        total = total + i

print(total)

"""***Question 23. FizzBuzz Job Interview***"""

#Write your code below this row 👇

number = range(1,101)
for ith in number:
    if ith % 3 == 0 and ith % 5 ==0:
        ith = "FizzBuzz"
    elif ith % 3 == 0:
        ith = "Fizz"
    elif ith % 5 == 0:
        ith = "Buzz"
    print(ith)

"""***Question 24. Password Generator***"""

#Password Generator Project
import random
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

print("Welcome to the PyPassword Generator!")
nr_letters= int(input("How many letters would you like in your password?\n")) 
nr_symbols = int(input(f"How many symbols would you like?\n"))
nr_numbers = int(input(f"How many numbers would you like?\n"))

#Eazy Level - Order not randomised:
#e.g. 4 letter, 2 symbol, 2 number = JduE&!91
password = ""

for char in range(1, nr_letters+1):
  random_char = random.choice(letters)
  password += random_char

for char in range(1, nr_symbols+1):
  random_symbols = random.choice(symbols)
  password += random_symbols

for char in range(1, nr_numbers+1):
  random_numbers = random.choice(numbers)
  password += random_numbers

print(password)

#Hard Level - Order of characters randomised:
#e.g. 4 letter, 2 symbol, 2 number = g^2jk8&P
password_list = []
password=""

for char in range(1, nr_letters+1):
  random_char = random.choice(letters)
  password_list.append(random_char)

for char in range(1, nr_symbols+1):
  random_symbols = random.choice(symbols)
  password_list.append(random_symbols)

for char in range(1, nr_numbers+1):
  random_numbers = random.choice(numbers)
  password_list.append(random_numbers)

for char in password_list:
  password += char

print(password)

